// Generated by tools/generate-skill-map.js — do not edit by hand.
// Edit Skill-Maps/data/graphics-printing.csv and re-run the generator.
window.SKILL_MAP_DATA = {
  centerLabel: "Graphics &amp;<br>Printing<br>Technology",
  topics: [
  {
    id: 1,
    name: "Habits of Mind",
    initials: "HM",
    color: "#8B5CF6",
    glow: "rgba(139,92,246,0.35)",
    bg: "rgba(139,92,246,0.12)",
    icon: "psychology",
    description: "Cultivate the professional attitudes and habits that underpin success in any creative or production environment. These foundational dispositions guide students to grow as self-directed learners, persistent problem-solvers, and skilled collaborators.",
    clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" },
        { label: "Management & Entrepreneurship", color: "#7B1FA2" },
        { label: "Education", color: "#0277BD" }
      ],
    skills: [
      {
        name: "Persistence",
        icon: "fitness_center",
        description: "Develop the resilience to work through obstacles without giving up. In design and production, challenges are opportunities to deepen understanding and strengthen technique.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Academic Curiosity",
        icon: "menu_book",
        description: "Cultivate a genuine drive to learn and investigate beyond the minimum. Great designers ask 'why' and 'what if' at every stage of the creative process.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" },
        { label: "Teaching, Training & Facilitation", color: "#0277BD" }
      ],
      },
      {
        name: "Commitment to Excellence",
        icon: "grade",
        description: "Hold every project—regardless of complexity—to the highest standard you are capable of. Excellence is a habit built through intentional, consistent practice.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" },
        { label: "Safety & Quality Assurance", color: "#D84315" }
      ],
      },
      {
        name: "Extending Knowledge",
        icon: "explore",
        description: "Actively seek new skills, techniques, and perspectives that expand what you can bring to your work. Professional growth does not stop at the classroom door.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" },
        { label: "Teaching, Training & Facilitation", color: "#0277BD" }
      ],
      },
      {
        name: "Application of Previous Knowledge",
        icon: "bolt",
        description: "Recognize when and how past skills apply to new challenges. The ability to transfer learning across contexts is the mark of a truly adaptable professional.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" },
        { label: "Leadership & Operations", color: "#7B1FA2" }
      ],
      }
    ],
  },
  {
    id: 2,
    name: "Adobe Illustrator",
    initials: "Ai",
    color: "#F97316",
    glow: "rgba(249,115,22,0.35)",
    bg: "rgba(249,115,22,0.12)",
    icon: "brush",
    description: "Build mastery in the industry-standard vector graphics application at the core of graphic design, branding, and print production. Students develop professional workflows from initial project setup through publication-ready output.",
    clusterTags: [
        { label: "Arts, Entertainment & Design", color: "#C2185B" },
        { label: "Marketing & Sales", color: "#6A1B9A" }
      ],
    skills: [
      {
        name: "Working in the Design Industry",
        icon: "work",
        description: "Understand the professional landscape of graphic design—roles, workflows, client relationships, and industry expectations. Learn how designers collaborate and communicate in real-world studios.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Leadership & Operations", color: "#7B1FA2" },
        { label: "Strategic Sales", color: "#6A1B9A" }
      ],
      },
      {
        name: "Project Setup & Interface",
        icon: "dashboard",
        description: "Navigate Illustrator's workspace with confidence. Set up documents with correct artboard dimensions, color modes, and units for your intended print or digital output.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" }
      ],
      },
      {
        name: "Organizing Documents",
        icon: "folder_open",
        description: "Use layers, groups, and naming conventions to keep complex files manageable. Organized files are faster to edit, easier to hand off, and more professional.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Business Information Management", color: "#7B1FA2" }
      ],
      },
      {
        name: "Creating & Modifying Visual Elements",
        icon: "draw",
        description: "Build and refine vector shapes, paths, and objects using Illustrator's core tools. Develop precision and control over the elements that make up your designs.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" }
      ],
      },
      {
        name: "Publishing Digital Media",
        icon: "publish",
        description: "Prepare and export artwork for digital and print output in the correct file formats and resolution settings. Understand the technical differences between screen and print-ready files.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Media Production & Broadcasting", color: "#C2185B" }
      ],
      }
    ],
  },
  {
    id: 3,
    name: "Silk Screening",
    initials: "Sk",
    color: "#EC4899",
    glow: "rgba(236,72,153,0.35)",
    bg: "rgba(236,72,153,0.12)",
    icon: "massage",
    description: "Learn the complete screen printing process from artwork preparation to finished garment. Students gain hands-on experience with frame preparation, ink mixing, and both single and multi-color production using plastisol inks.",
    clusterTags: [
        { label: "Arts, Entertainment & Design", color: "#C2185B" },
        { label: "Advanced Manufacturing", color: "#D84315" }
      ],
    skills: [
      {
        name: "Prepare Silk Screens",
        icon: "grid_on",
        description: "Coat screens with emulsion, dry them in a light-safe environment, and inspect for defects before exposure. Proper preparation is the foundation of a clean, consistent print.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Safety & Quality Assurance", color: "#D84315" }
      ],
      },
      {
        name: "Design Positives & Transparencies",
        icon: "image",
        description: "Create print-ready positive films or transparencies used to expose the screen, ensuring sufficient ink density for a complete and accurate burn.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Expose and Wash Out Frames",
        icon: "wb_sunny",
        description: "Use a UV exposure unit to transfer the design onto the coated screen, then wash out unexposed emulsion to reveal a clean, open stencil ready for printing.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Align & Set Up Single and Multi-Color Print Jobs",
        icon: "tune",
        description: "Register screens accurately on the press to ensure precise alignment across one or multiple color layers, preventing misregistration on the finished garment.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      },
      {
        name: "Prepare & Mix Plastisol Ink",
        icon: "colorize",
        description: "Mix and prepare plastisol inks to achieve the correct color, viscosity, and opacity for the substrate and design being printed.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Safety & Quality Assurance", color: "#D84315" }
      ],
      },
      {
        name: "Single & Multi-Color Printing",
        icon: "photo_library",
        description: "Execute print runs with consistent squeegee pressure, angle, and speed for sharp, even coverage across single and multi-color jobs.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Cure & Finish Prints",
        icon: "local_fire_department",
        description: "Pass printed garments through a conveyor dryer or use a flash unit to fully cure plastisol ink, producing washfast, durable results ready for delivery.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Safety & Quality Assurance", color: "#D84315" }
      ],
      }
    ],
  },
  {
    id: 4,
    name: "Embroidery",
    initials: "Em",
    color: "#14B8A6",
    glow: "rgba(20,184,166,0.35)",
    bg: "rgba(20,184,166,0.12)",
    icon: "laundry",
    description: "Explore the intersection of craft and technology in machine embroidery. Students develop skills in digitizing artwork for stitch output, setting up and operating commercial equipment, and maintaining machines for consistent, high-quality results.",
    clusterTags: [
        { label: "Arts, Entertainment & Design", color: "#C2185B" },
        { label: "Advanced Manufacturing", color: "#D84315" }
      ],
    skills: [
      {
        name: "Design for Embroidery",
        icon: "design_services",
        description: "Understand the constraints of embroidery as a medium—minimum detail size, stitch count, and how design decisions translate into thread, needle, and finished texture.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Fashion & Interiors", color: "#C2185B" }
      ],
      },
      {
        name: "Embroidery Digitizing",
        icon: "code",
        description: "Use digitizing software to convert artwork into a stitch file, defining stitch types, directions, densities, and color sequences for accurate machine output.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Software Solutions", color: "#4527A0" }
      ],
      },
      {
        name: "Machine Maintenance and Setup",
        icon: "build",
        description: "Perform routine maintenance including cleaning, oiling, and tension adjustments to keep machines running reliably and producing consistent, high-quality embroidery.",
        clusterTags: [
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      },
      {
        name: "Machine Operation",
        icon: "settings",
        description: "Thread, hoop, and operate commercial embroidery machines safely and efficiently, monitoring production runs and troubleshooting common issues as they arise.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      }
    ],
  },
  {
    id: 5,
    name: "Direct to Film",
    initials: "Df",
    color: "#3B82F6",
    glow: "rgba(59,130,246,0.35)",
    bg: "rgba(59,130,246,0.12)",
    icon: "layers",
    description: "Master the end-to-end DTF printing workflow, from digital file preparation to finished heat-applied transfer. Students operate and maintain every piece of equipment in the production chain, producing professional-grade garment decorations.",
    clusterTags: [
        { label: "Arts, Entertainment & Design", color: "#C2185B" },
        { label: "Advanced Manufacturing", color: "#D84315" },
        { label: "Digital Technology", color: "#4527A0" }
      ],
    skills: [
      {
        name: "Design for the DTF Process",
        icon: "image",
        description: "Prepare artwork files with the correct resolution, color profile, and white underbase settings required for successful DTF printing and vibrant transfer results.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" }
      ],
      },
      {
        name: "Machine Maintenance and Setup",
        icon: "handyman",
        description: "Maintain the DTF printer through regular cleaning cycles, printhead care, and film path checks to ensure consistent, clog-free output across production runs.",
        clusterTags: [
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      },
      {
        name: "RasterLink 7 Print Setup and Operation",
        icon: "computer",
        description: "Configure RasterLink 7 RIP software with appropriate color profiles, print modes, and layout settings to optimize film output for DTF transfer production.",
        clusterTags: [
        { label: "Software Solutions", color: "#4527A0" },
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Heater/Shaker Setup, Operation, and Maintenance",
        icon: "whatshot",
        description: "Operate the powder adhesive heater and shaker at correct temperatures and timing, and perform routine maintenance to ensure even, consistent adhesive application.",
        clusterTags: [
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      },
      {
        name: "Heat Press Setup, Operation, and Maintenance",
        icon: "compress",
        description: "Set heat press time, temperature, and pressure for different garment types and transfer materials, and maintain the platen surface for consistent, professional application.",
        clusterTags: [
        { label: "Industrial Machinery", color: "#D84315" },
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Heat Press Laser Alignment Setup & Utilization",
        icon: "gps_fixed",
        description: "Use laser alignment tools to position transfers accurately and repeatably, minimizing placement errors and improving throughput on production runs.",
        clusterTags: [
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      },
      {
        name: "DTF Transfer Application",
        icon: "touch_app",
        description: "Apply cured DTF transfers to garments using correct heat and pressure parameters, achieving a durable bond with a smooth, professional finish.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Safety & Quality Assurance", color: "#D84315" }
      ],
      }
    ],
  },
  {
    id: 6,
    name: "Digital Signmaking & Printing",
    initials: "Ds",
    color: "#22C55E",
    glow: "rgba(34,197,94,0.35)",
    bg: "rgba(34,197,94,0.12)",
    icon: "signpost",
    description: "Apply design and wide-format production skills to create professional signage, graphics, and branded materials. Students work with industry-standard software and solvent printing equipment across a broad range of substrates and real-world applications.",
    clusterTags: [
        { label: "Arts, Entertainment & Design", color: "#C2185B" },
        { label: "Advanced Manufacturing", color: "#D84315" },
        { label: "Marketing & Sales", color: "#6A1B9A" }
      ],
    skills: [
      {
        name: "Design for Digital Signmaking & Printing",
        icon: "landscape",
        description: "Create artwork sized, scaled, and colored correctly for wide-format output, accounting for viewing distance, substrate characteristics, and environmental conditions.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Media Production & Broadcasting", color: "#C2185B" }
      ],
      },
      {
        name: "Media & Substrate Management",
        icon: "inventory",
        description: "Select, load, and handle print media correctly to prevent feed errors, minimize wasted material, and ensure consistent, defect-free print output.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" },
        { label: "Purchasing & Warehousing", color: "#795548" }
      ],
      },
      {
        name: "RasterLink 7 Print/Cut Setup and Operation",
        icon: "content_cut",
        description: "Configure RasterLink 7 for print-only, cut-only, and print-then-cut workflows, optimizing settings for each substrate type and finished application.",
        clusterTags: [
        { label: "Software Solutions", color: "#4527A0" },
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Solvent Printer Setup, Operation, and Maintenance",
        icon: "print",
        description: "Operate the solvent printer through daily startup, media loading, print runs, and maintenance routines including printhead cleaning and ink system management.",
        clusterTags: [
        { label: "Industrial Machinery", color: "#D84315" }
      ],
      },
      {
        name: "Media Application",
        icon: "content_paste",
        description: "Apply printed media to surfaces cleanly and without bubbles, wrinkles, or lifting, using the tools and techniques appropriate to each substrate and environment.",
        clusterTags: [
        { label: "Production & Automation", color: "#D84315" }
      ],
      },
      {
        name: "Design for Banners, Signs, & More",
        icon: "panorama",
        description: "Apply design principles and technical knowledge to produce output-ready artwork for a wide range of signage, display, and branded environment applications.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Marketing & Advertising", color: "#6A1B9A" }
      ],
      }
    ],
  },
  {
    id: 7,
    name: "Logistics & Operations",
    initials: "Lo",
    color: "#EAB308",
    glow: "rgba(234,179,8,0.35)",
    bg: "rgba(234,179,8,0.12)",
    icon: "local_shipping",
    description: "Develop the operational skills that keep a production business running efficiently. Students manage client relationships, source and track materials, uphold quality standards, and oversee projects from intake through final delivery.",
    clusterTags: [
        { label: "Management & Entrepreneurship", color: "#7B1FA2" },
        { label: "Supply Chain & Transportation", color: "#795548" }
      ],
    skills: [
      {
        name: "Client Communication",
        icon: "forum",
        description: "Interact professionally with clients from initial inquiry through job completion—taking orders accurately, setting clear expectations, and following up to confirm satisfaction.",
        clusterTags: [
        { label: "Leadership & Operations", color: "#7B1FA2" },
        { label: "Strategic Sales", color: "#6A1B9A" }
      ],
      },
      {
        name: "Procurement, Shipping & Receiving",
        icon: "unarchive",
        description: "Source materials from vendors, manage purchase orders, and accurately receive and inspect incoming goods to maintain production readiness.",
        clusterTags: [
        { label: "Purchasing & Warehousing", color: "#795548" }
      ],
      },
      {
        name: "Quality Control",
        icon: "fact_check",
        description: "Inspect finished products against established standards before they leave the shop, identifying and resolving defects to ensure every order meets expectations.",
        clusterTags: [
        { label: "Safety & Quality Assurance", color: "#D84315" }
      ],
      },
      {
        name: "Outgoing Packaging & Shipping",
        icon: "send",
        description: "Package finished orders safely and professionally, generate shipping labels, and coordinate carrier pickup or drop-off for timely, damage-free delivery.",
        clusterTags: [
        { label: "Purchasing & Warehousing", color: "#795548" },
        { label: "Planning & Logistics", color: "#795548" }
      ],
      },
      {
        name: "Project Management",
        icon: "assignment",
        description: "Coordinate tasks, timelines, and resources across a job from intake through completion, keeping production on schedule and all stakeholders informed.",
        clusterTags: [
        { label: "Project Management", color: "#7B1FA2" }
      ],
      }
    ],
  },
  {
    id: 8,
    name: "Marketing & Advertisement",
    initials: "Mk",
    color: "#EF4444",
    glow: "rgba(239,68,68,0.35)",
    bg: "rgba(239,68,68,0.12)",
    icon: "campaign",
    description: "Build the skills to research, promote, and visually communicate a brand's products and services. Students identify target audiences, capture compelling product imagery, and design marketing materials across both physical and digital channels.",
    clusterTags: [
        { label: "Marketing & Sales", color: "#6A1B9A" },
        { label: "Arts, Entertainment & Design", color: "#C2185B" }
      ],
    skills: [
      {
        name: "Market Research",
        icon: "analytics",
        description: "Identify target audiences, analyze competitors, and gather insights that inform positioning, messaging, and promotional strategy for products and services.",
        clusterTags: [
        { label: "Market Research, Analytics & Ethics", color: "#6A1B9A" }
      ],
      },
      {
        name: "Product Photography",
        icon: "photo_camera",
        description: "Capture clean, well-lit product images suitable for use in marketing materials, online storefronts, social media, and printed catalogs.",
        clusterTags: [
        { label: "Design & Digital Arts", color: "#C2185B" },
        { label: "Marketing & Advertising", color: "#6A1B9A" }
      ],
      },
      {
        name: "Physical & Digital Marketing Design",
        icon: "photo_album",
        description: "Design cohesive promotional materials for both print distribution and digital channels, applying brand guidelines and effective visual communication principles.",
        clusterTags: [
        { label: "Marketing & Advertising", color: "#6A1B9A" },
        { label: "Design & Digital Arts", color: "#C2185B" }
      ],
      }
    ],
  },
  {
    id: 9,
    name: "Storefront & Enterprise",
    initials: "Se",
    color: "#06B6D4",
    glow: "rgba(6,182,212,0.35)",
    bg: "rgba(6,182,212,0.12)",
    icon: "storefront",
    description: "Experience running a real business through the school-based enterprise. Students manage retail operations, maintain accurate inventory records, process transactions through point-of-sale systems, and apply foundational bookkeeping principles.",
    clusterTags: [
        { label: "Management & Entrepreneurship", color: "#7B1FA2" },
        { label: "Marketing & Sales", color: "#6A1B9A" },
        { label: "Financial Services", color: "#E65100" }
      ],
    skills: [
      {
        name: "Operate School-Based Enterprise",
        icon: "business",
        description: "Run day-to-day business operations in the school store, applying real-world retail and production skills in a supported, professional learning environment.",
        clusterTags: [
        { label: "Entrepreneurship & Small Business", color: "#7B1FA2" },
        { label: "Retail & Customer Experience", color: "#6A1B9A" }
      ],
      },
      {
        name: "Inventory Management",
        icon: "warehouse",
        description: "Track stock levels, record incoming and outgoing goods, and flag low inventory to ensure the enterprise is always ready to fulfill customer orders.",
        clusterTags: [
        { label: "Purchasing & Warehousing", color: "#795548" },
        { label: "Business Information Management", color: "#7B1FA2" }
      ],
      },
      {
        name: "Point of Sale",
        icon: "point_of_sale",
        description: "Process customer transactions accurately using point-of-sale software, handle returns and exchanges, and reconcile end-of-day sales records.",
        clusterTags: [
        { label: "Retail & Customer Experience", color: "#6A1B9A" },
        { label: "Business Information Management", color: "#7B1FA2" }
      ],
      },
      {
        name: "Bookkeeping",
        icon: "calculate",
        description: "Record financial transactions, track income and expenses, and maintain accurate books using foundational accounting principles and business practices.",
        clusterTags: [
        { label: "Accounting", color: "#E65100" }
      ],
      }
    ],
  }
],
};
