// Generated by tools/generate-skill-map.js — do not edit by hand.
// Edit Skill-Maps/data/intro-to-robotics.csv and re-run the generator.
window.SKILL_MAP_DATA = {
  centerLabel: "IR",
  topics: [
  {
    id: 1,
    name: "Motion & Mechanical Relationships",
    initials: "MM",
    color: "#EF6C00",
    glow: "rgba(239,108,0,0.35)",
    bg: "rgba(239,108,0,0.12)",
    icon: "settings",
    description: "Gear ratios, gear physics, and mechanical linkages that translate motor input into precise robot motion — from simple machines through planetary gearboxes.",
    clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
    skills: [
      {
        name: "Simple Machines",
        icon: "precision_manufacturing",
        description: "Identify the six common simple machines (lever, pulley, wheel & axle, inclined plane, wedge, screw) and how each is applied within robotic mechanisms.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Gear Fundamentals & Ratios",
        icon: "settings",
        description: "Define what a gear is, calculate gear ratios on a gear train, and explain the role of idler gears in transmitting motion.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Gear Physics: Speed & Torque",
        icon: "speed",
        description: "Observe how changing a gear ratio trades off output speed against output torque in a gear train.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Compound Gearing",
        icon: "hub",
        description: "Calculate gear ratios using compound gearing, and explain what causes a motor to stall and how to prevent it.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Motor Speed & Torque (Gear Ratio Applications)",
        icon: "bolt",
        description: "Define free speed and stall torque, and calculate a motor's output speed and torque once a gear ratio and safety factor are applied.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Planetary Gearboxes",
        icon: "blur_circular",
        description: "Identify the parts of a planetary gearbox (sun gear, planet gear, carrier, outer ring) and calculate gear ratios when using a gearbox.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Gear Reduction, Wheel Size & Distance",
        icon: "straighten",
        description: "Explain how gear reduction and wheel size affect encoder-based distance measurement, and program a robot to drive a set distance accordingly.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      }
    ],
  },
  {
    id: 2,
    name: "Design & Assembly",
    initials: "DA",
    color: "#2E7D32",
    glow: "rgba(46,125,50,0.35)",
    bg: "rgba(46,125,50,0.12)",
    icon: "construction",
    description: "Applying the Engineering Design Process to build, assemble, and iterate on robot mechanisms, drivetrains, and manipulators using the REV DUO EDU Kit.",
    clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" },
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
    skills: [
      {
        name: "Safety Procedures & Kit Management",
        icon: "health_and_safety",
        description: "Follow lab safety procedures, inventory an EDU Kit, and identify the tools available and their appropriate use.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" },
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Mechanical Assembly Basics",
        icon: "build",
        description: "Identify core mechanical parts — brackets, extrusion, and hardware — and complete a first mechanical build using only these components.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Engineering Design Process",
        icon: "lightbulb",
        description: "Define each step of the Engineering Design Process and apply it to an example design prompt.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" },
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Drivetrain Assembly & Design",
        icon: "directions_car",
        description: "Differentiate a differential drivetrain from an omnidirectional drivetrain and assemble a Class Bot drivetrain.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Mechanisms & Continuous Rotation Servos",
        icon: "settings_input_component",
        description: "Discuss the use and types of mechanisms in robotics, then build and program a small mechanism using a servo set to continuous rotation mode.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Applying the Design Process to a Build",
        icon: "engineering",
        description: "Brainstorm a robot design using the Engineering Design Process, document decisions on a project worksheet, and iterate a build based on testing results.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" },
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Robotic Arm & Servo Claw Assembly",
        icon: "precision_manufacturing",
        description: "Assemble a robotic arm with an adjustable fulcrum and a servo-controlled claw, and observe how fulcrum placement changes arm movement.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      }
    ],
  },
  {
    id: 3,
    name: "Control Systems",
    initials: "CS",
    color: "#0277BD",
    glow: "rgba(2,119,189,0.35)",
    bg: "rgba(2,119,189,0.12)",
    icon: "electrical_services",
    description: "The physical hardware layer of a robot — motors, servos, hubs, and sensors — and how they are wired, configured, and connected to make the robot controllable.",
    clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
    skills: [
      {
        name: "Actuators: Motors & Servos",
        icon: "settings_applications",
        description: "Differentiate a motor from a servo, build a testbed for actuators, and wire actuators to the Control Hub.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Control Hub & Driver Hub Setup",
        icon: "developer_board",
        description: "Set up the Control Hub and Driver Hub, connect them together, and complete the configuration process for a testbed.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Sensor Fundamentals (Digital/Analog/I2C)",
        icon: "sensors",
        description: "Differentiate digital, analog, and I2C sensors, and identify where sensors are used in everyday life.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Touch Sensors & Limit Switches",
        icon: "touch_app",
        description: "Explore how a touch sensor functions mechanically and wire one as a limit switch to protect a robot's mechanisms.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      },
      {
        name: "Encoders & IMU Hardware",
        icon: "explore",
        description: "Differentiate incremental from absolute encoders, explain what an IMU tracks along yaw, pitch, and roll, and read raw sensor values via telemetry.",
        clusterTags: [
        { label: "Engineering & Technology", color: "#37474F" }
      ],
      }
    ],
  },
  {
    id: 4,
    name: "Programming",
    initials: "PR",
    color: "#6A1B9A",
    glow: "rgba(106,27,154,0.35)",
    bg: "rgba(106,27,154,0.12)",
    icon: "code",
    description: "Writing and structuring code — from gamepad-driven drivetrains to autonomous routines — using variables, loops, conditionals, and sensor feedback in Blocks programming.",
    clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
    skills: [
      {
        name: "Blocks Programming Basics",
        icon: "terminal",
        description: "Navigate the Blocks programming interface, create a first OpMode, and program a motor and servo to respond to gamepad input with telemetry feedback.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Gamepad Inputs & Data Types",
        icon: "sports_esports",
        description: "Identify boolean and float data types output by the gamepad and use telemetry to observe their values in code.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Drive Programming Styles (Tank/Arcade)",
        icon: "gamepad",
        description: "Program a drivetrain using both tank drive and arcade style controls, and explain how joystick input translates into drivetrain movement.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Variables & Telemetry",
        icon: "data_object",
        description: "Define what a variable is, use telemetry to observe its value, and optimize a program by replacing hardcoded values with variables.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Pseudocode & Autonomous Programming",
        icon: "edit_note",
        description: "Write pseudocode for a robot's program and use it to write a first autonomous OpMode that uses 'sleep' as a basic timer.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Loops & Nested Loops",
        icon: "repeat",
        description: "Use loops to reduce repeated code, implement nested loops, and apply exit conditions to control when a loop ends.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Conditional Logic (If/Else)",
        icon: "alt_route",
        description: "Program if/else logic that responds to a sensor input and trace how a program's flow changes through a conditional branch.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "ElapsedTime & Functions",
        icon: "timer",
        description: "Set up a timer using ElapsedTime, explain the difference between Sleep and ElapsedTime, and refactor a program into functions for better organization.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      },
      {
        name: "Encoder & IMU-Based Navigation",
        icon: "navigation",
        description: "Program a robot arm to move to a set position using encoders, and program a robot to navigate an autonomous area using IMU orientation data.",
        clusterTags: [
        { label: "Programming & Computer Science", color: "#1565C0" }
      ],
      }
    ],
  }
],
};
