// Generated by tools/generate-skill-map.js — do not edit by hand.
// Edit Skill-Maps/data/cam-technology.csv and re-run the generator.
window.SKILL_MAP_DATA = {
  centerLabel: "CAM",
  topics: [
  {
    id: 1,
    name: "Habits of Mind",
    initials: "HM",
    color: "#546E7A",
    glow: "rgba(84,110,122,0.35)",
    bg: "rgba(84,110,122,0.12)",
    icon: "psychology",
    description: "Foundational professional mindsets and academic behaviors that support success across all manufacturing and technical disciplines, aligned with the Career Ready Practices embedded throughout CTE programs.",
    clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" },
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
    skills: [
      {
        name: "Persistence",
        icon: "self_improvement",
        description: "Maintaining effort and focus through challenging technical tasks; demonstrating resilience when encountering obstacles in CAD/CAM projects and shop work.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Academic Curiosity",
        icon: "manage_search",
        description: "Asking questions and seeking deeper understanding of manufacturing concepts and technologies beyond what is directly covered in class.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Commitment to Excellence",
        icon: "workspace_premium",
        description: "Holding oneself to high standards of quality in workmanship, safety, and professional behavior in the shop and computer lab.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Extending Knowledge",
        icon: "menu_book",
        description: "Actively seeking new information, techniques, and skills to stay current with evolving manufacturing technologies and industry practices.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      },
      {
        name: "Application of Previous Knowledge",
        icon: "hub",
        description: "Drawing on prior learning from math, science, and previous courses to solve new manufacturing and design challenges.",
        clusterTags: [
        { label: "Career Ready Practices", color: "#546E7A" }
      ],
      }
    ],
  },
  {
    id: 2,
    name: "OnShape",
    initials: "OS",
    color: "#0277BD",
    glow: "rgba(2,119,189,0.35)",
    bg: "rgba(2,119,189,0.12)",
    icon: "view_in_ar",
    description: "Cloud-based parametric CAD platform used to create 2D sketches, 3D solid models, assemblies, and technical drawings that drive modern manufacturing workflows from design through production.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Digital Technology", color: "#0277BD" }
      ],
    skills: [
      {
        name: "2D Sketching",
        icon: "draw",
        description: "Creating fully-defined 2D profiles using lines, arcs, circles, and polygons as the foundation for 3D feature-based modeling in OnShape.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Digital Technology", color: "#0277BD" }
      ],
      },
      {
        name: "Sketch Relations & Constraints",
        icon: "straighten",
        description: "Applying geometric relations (coincident, parallel, perpendicular) and dimensional constraints to fully define sketches and lock in design intent.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Digital Technology", color: "#0277BD" }
      ],
      },
      {
        name: "3D Modeling",
        icon: "view_in_ar",
        description: "Building parametric solid models using features such as extrude, revolve, fillet, chamfer, and shell to create manufacturable part geometry.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Digital Technology", color: "#0277BD" }
      ],
      },
      {
        name: "Assemblies",
        icon: "account_tree",
        description: "Mating and arranging multiple parts into assemblies using mate connectors and relations to simulate real-world configurations and check for interference.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Digital Technology", color: "#0277BD" }
      ],
      },
      {
        name: "Technical Drawings",
        icon: "description",
        description: "Generating multi-view orthographic drawings with dimensions, tolerances, section views, and title block information from 3D part and assembly models.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Digital Technology", color: "#0277BD" }
      ],
      }
    ],
  },
  {
    id: 3,
    name: "MasterCAM",
    initials: "MC",
    color: "#E65100",
    glow: "rgba(230,81,0,0.35)",
    bg: "rgba(230,81,0,0.12)",
    icon: "precision_manufacturing",
    description: "Industry-leading CAM software used to program CNC machining operations — including toolpath creation, simulation, and post-processing — for milling and turning centers.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Industrial Machinery", color: "#BF360C" }
      ],
    skills: [
      {
        name: "Mastercam Interface and Layout",
        icon: "dashboard",
        description: "Navigating the Mastercam workspace including toolbars, the toolpath manager, levels manager, and graphics view to efficiently set up and manage complex part programs.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Levels Control",
        icon: "layers",
        description: "Organizing geometry and toolpaths using Mastercam's levels system to keep complex multi-operation programs clean, manageable, and easy to edit.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Machine Group Setup – Stock Definition",
        icon: "inventory_2",
        description: "Configuring machine group properties including stock shape, dimensions, and material to define the raw workpiece before generating any toolpaths.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Machine Group Setup – Workholding",
        icon: "pan_tool",
        description: "Defining workholding strategies and fixture offsets to accurately locate and secure the part on the machine table prior to machining.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Machine Group Setup – Tool Library",
        icon: "home_repair_service",
        description: "Building and managing a tool library with cutting tool geometry, speeds, and feeds to support accurate toolpath simulation and correct NC output.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Dynamic Milling – Contouring & Pocketing",
        icon: "precision_manufacturing",
        description: "Applying high-efficiency Dynamic Milling strategies for roughing and pocketing that maximize tool life, reduce heat, and minimize cycle time.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Work Offsets",
        icon: "my_location",
        description: "Setting and managing work coordinate offsets (G54–G59) to accurately reference the part origin on the machine tool relative to known datum surfaces.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  },
  {
    id: 5,
    name: "Cordless Tools",
    initials: "Ct",
    color: "#F57F17",
    glow: "rgba(245,127,23,0.35)",
    bg: "rgba(245,127,23,0.12)",
    icon: "handyman",
    description: "Safe selection, setup, and operation of battery-powered hand tools used throughout fabrication, assembly, and maintenance tasks in the manufacturing shop.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Construction", color: "#FF8F00" }
      ],
    skills: [
      {
        name: "Drill",
        icon: "hardware",
        description: "Safely operating a cordless drill for boring holes and driving fasteners, including proper bit selection, chuck technique, and appropriate speed and torque settings.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Impact Driver",
        icon: "bolt",
        description: "Using a cordless impact driver for high-torque fastener driving, including correct hex bit selection and adjusting drive mode to prevent over-driving fasteners.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Jigsaw",
        icon: "content_cut",
        description: "Cutting curves and irregular profiles in wood and thin metal using a cordless jigsaw, including blade selection, orbital settings, and proper workpiece support.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Angle Grinder",
        icon: "settings_input_component",
        description: "Safely operating a cordless angle grinder for cutting, grinding, and deburring metal — including guard use, PPE requirements, and correct disc selection.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Brad Nailer/Stapler",
        icon: "push_pin",
        description: "Using a pneumatic or cordless brad nailer and stapler for fastening materials in fabrication and assembly, including safe loading, operating, and jam clearing.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  },
  {
    id: 6,
    name: "Power Tools",
    initials: "Pt",
    color: "#BF360C",
    glow: "rgba(191,54,12,0.35)",
    bg: "rgba(191,54,12,0.12)",
    icon: "hardware",
    description: "Safe setup and operation of stationary and portable power tools used for precise cutting, shaping, and finishing of wood, metal, and composite materials in a manufacturing environment.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Construction", color: "#FF8F00" }
      ],
    skills: [
      {
        name: "Sliding Compound Miter Saw",
        icon: "content_cut",
        description: "Setting up and operating a sliding compound miter saw for accurate crosscuts, miter cuts, and bevel cuts — including fence setup, blade guard use, and material clamping.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Table Saw",
        icon: "table_bar",
        description: "Performing safe ripping and crosscutting on the table saw, including fence setup, blade height, splitter use, and proper use of push sticks and featherboards.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Circular Saw",
        icon: "construction",
        description: "Making freehand and guided cuts with a circular saw, including blade selection, depth setting, proper stance, and use of a straightedge guide.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Drill Press",
        icon: "expand_circle_down",
        description: "Setting up and operating a drill press for precise hole boring at controlled depths and angles, including table adjustment, speed selection, and secure workpiece clamping.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Belt Sander",
        icon: "cleaning_services",
        description: "Surface finishing and material removal using a belt and bench sander, including grit selection, workpiece control, and dust collection techniques.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  },
  {
    id: 7,
    name: "Jigs & Fixturing",
    initials: "Jf",
    color: "#4527A0",
    glow: "rgba(69,39,160,0.35)",
    bg: "rgba(69,39,160,0.12)",
    icon: "tune",
    description: "Design and use of jigs, clamps, and custom fixtures to hold workpieces accurately and repeatably during machining and assembly operations, improving quality and production efficiency.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Engineering", color: "#1565C0" }
      ],
    skills: [
      {
        name: "Work Holding",
        icon: "pan_tool",
        description: "Selecting and applying appropriate work-holding strategies — vises, clamps, step blocks, and T-slot hardware — to secure parts safely and consistently during machining operations.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Clamps & Fixtures",
        icon: "link",
        description: "Designing and using custom fixtures and clamps to locate and hold workpieces precisely and repeatably for improved dimensional consistency across production runs.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Hard Stops",
        icon: "stop_circle",
        description: "Setting mechanical hard stops to control travel limits on machine tools, ensuring repeatable positioning without re-indicating the part for each successive operation.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Touch Offs",
        icon: "touch_app",
        description: "Setting tool length offsets and work coordinate origins by touching off cutting tools to known reference surfaces or using an electronic tool-length setter.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  },
  {
    id: 8,
    name: "Manufacturing Practices",
    initials: "Mp",
    color: "#2E7D32",
    glow: "rgba(46,125,50,0.35)",
    bg: "rgba(46,125,50,0.12)",
    icon: "factory",
    description: "Industry-standard practices that govern how modern manufacturing facilities operate — including lean principles, quality control, inspection, and the ability to read and interpret technical documentation.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Production & Automation", color: "#2E7D32" }
      ],
    skills: [
      {
        name: "Job Management",
        icon: "assignment",
        description: "Planning and tracking production tasks, managing workflow across operations, and meeting deadlines using job routers and scheduling tools in a manufacturing environment.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Just in Time Manufacturing",
        icon: "schedule",
        description: "Applying JIT principles to minimize raw material and WIP inventory, reduce lead times, and synchronize production output with customer demand.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Lean Manufacturing",
        icon: "trending_down",
        description: "Identifying and eliminating the eight wastes using lean tools such as 5S, value stream mapping, standardized work, and kaizen events to improve process flow.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Quality Control/Inspection",
        icon: "fact_check",
        description: "Applying measurement tools — calipers, micrometers, and gauges — and inspection methods to verify that parts conform to drawing specifications and tolerances.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Reading Technical Drawings",
        icon: "article",
        description: "Interpreting orthographic projections, dimensions, tolerances, surface finish symbols, GD&T callouts, and title block information on engineering drawings.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  },
  {
    id: 9,
    name: "Building & Assembling",
    initials: "Ba",
    color: "#558B2F",
    glow: "rgba(85,139,47,0.35)",
    bg: "rgba(85,139,47,0.12)",
    icon: "build",
    description: "Hands-on skills for organizing components, sequencing assembly operations, and completing finished products or sub-assemblies to specification in a manufacturing or fabrication context.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Production & Automation", color: "#2E7D32" }
      ],
    skills: [
      {
        name: "Component Layout & Organization",
        icon: "view_list",
        description: "Sorting, identifying, and staging all required parts, hardware, and sub-assemblies before beginning assembly to ensure efficient workflow and prevent errors.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Assembly Sequencing",
        icon: "low_priority",
        description: "Determining and following the correct order of assembly operations to ensure proper fit, clearances, and tool access throughout the build process.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  },
  {
    id: 10,
    name: "Technical Theatre",
    initials: "Tt",
    color: "#AD1457",
    glow: "rgba(173,20,87,0.35)",
    bg: "rgba(173,20,87,0.12)",
    icon: "theater_comedy",
    description: "Practical technical theatre skills spanning stage lighting, live sound reinforcement, and scenic design and construction — used in live performance production, event stagecraft, and the performing arts industry.",
    clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" },
        { label: "Lighting & Sound Technology", color: "#880E4F" }
      ],
    skills: [
      {
        name: "Hanging Lights",
        icon: "light",
        description: "Safely hanging and positioning stage lighting instruments on battens, electrics, and pipes using C-clamps, safety cables, and proper rigging techniques.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Setting Lights",
        icon: "wb_incandescent",
        description: "Focusing and adjusting lighting instruments — including pan, tilt, zoom, barrel rotation, and shutter cuts — to achieve the intended stage illumination and throw distance.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Patching Lights",
        icon: "cable",
        description: "Connecting stage lighting instruments to dimmer circuits and programming DMX patch assignments in a lighting console to establish individual fixture control.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Lighting Design",
        icon: "highlight",
        description: "Developing a lighting design including plot creation, instrument selection, color and gobo choices, channel assignments, and cue sequence programming to support a production's visual storytelling.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Patching Microphones",
        icon: "mic",
        description: "Connecting and routing microphones through a mixing console, including signal flow, gain staging, phantom power management, and cable organization for live sound applications.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Setting Levels",
        icon: "graphic_eq",
        description: "Balancing channel fader levels, gain structure, and output bus levels on a mixing console during soundcheck and live performance to achieve a clean well-balanced mix.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "EQ Basics",
        icon: "equalizer",
        description: "Applying parametric and graphic equalization to shape frequency response, remove problem frequencies, reduce feedback, and improve clarity in live sound reinforcement.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Elevations",
        icon: "straighten",
        description: "Reading and drafting scaled scenic elevations — front-view drawings showing dimensions, materials, and construction details — that communicate build intent to the shop crew.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Framing",
        icon: "construction",
        description: "Building structural frames for flats, platforms, and other scenic units using standard lumber dimensions, lap joints, butt joints, and appropriate fasteners.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Standard Scenic Components (Flats, Platforms, etc.)",
        icon: "view_module",
        description: "Identifying and constructing standard scenic units including Hollywood flats, Broadway flats, hard-covered platforms, and stair units used in theatrical production.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      },
      {
        name: "Scenic Painting",
        icon: "format_paint",
        description: "Applying ground coats, lay-in coats, and finish techniques — including texture, faux finishes, and scenic effects — to achieve realistic or stylized visual finishes for the stage.",
        clusterTags: [
        { label: "Arts, Entertainment, & Design", color: "#AD1457" }
      ],
      }
    ],
  },
  {
    id: 11,
    name: "OSHA 10",
    initials: "Oa",
    color: "#B71C1C",
    glow: "rgba(183,28,28,0.35)",
    bg: "rgba(183,28,28,0.12)",
    icon: "health_and_safety",
    description: "OSHA 10-Hour General Industry certification content covering hazard recognition, workers' rights, and the major safety standards that protect employees in manufacturing and industrial workplaces.",
    clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" },
        { label: "Safety & Quality Assurance", color: "#B71C1C" }
      ],
    skills: [
      {
        name: "Introduction to OSHA & Workers' Rights",
        icon: "policy",
        description: "Understanding OSHA's mission, the General Duty Clause, employee rights to a safe workplace, the inspection process, and how to file a complaint without fear of retaliation.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Walking & Working Surfaces / Fall Protection",
        icon: "stairs",
        description: "Identifying slip, trip, and fall hazards on walking and working surfaces and applying controls including guardrails, personal fall arrest systems, and proper housekeeping practices.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Electrical Safety",
        icon: "bolt",
        description: "Recognizing electrical hazards such as exposed conductors, overloaded circuits, and improper grounding — and applying safe work practices including LOTO/TAGOUT procedures.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Hazard Communication (HazCom / GHS)",
        icon: "warning",
        description: "Reading and interpreting Safety Data Sheets (SDS), GHS-compliant container labels, and pictograms to understand chemical hazards and required safe handling procedures.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Personal Protective Equipment (PPE)",
        icon: "safety_check",
        description: "Selecting, fitting, and caring for appropriate PPE including eye and face protection, hearing protection, hard hats, gloves, and respiratory protection matched to specific hazards.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Machine Guarding",
        icon: "security",
        description: "Identifying machine hazards including point-of-operation dangers, in-running nip points, and rotating parts — and applying safeguarding methods such as fixed guards and interlocks.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Lockout/Tagout (LOTO)",
        icon: "lock",
        description: "Following the six-step energy control procedure to isolate and de-energize machinery before maintenance or servicing to prevent unexpected startup and release of stored energy.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      },
      {
        name: "Fire Safety & Emergency Action Plans",
        icon: "local_fire_department",
        description: "Identifying fire hazard classes, understanding extinguisher selection and the PASS technique, and following emergency action and evacuation plan procedures.",
        clusterTags: [
        { label: "Advanced Manufacturing", color: "#E65100" }
      ],
      }
    ],
  }
],
};
